spring:
    application:
        name: didcs-zuul
    cloud:
      loadbalancer:
        retry:
          enabled: true
server:
    port: 8762
eureka:
    instance:
        statusPageUrlPath: ${management.context-path}/info
        healthCheckUrlPath: ${management.context-path}/health
        preferIpAddress: true
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

zuul:
    semaphore:
        max-semaphores: 1000
    host:
        max-total-connections: 500

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

#actuator
management:
    security:
        enabled: false
    context-path: /manage