server:
    port: 8768
spring:
    application:
        name: clean-service
    datasource:
        name: test
        url: jdbc:mysql://172.17.24.99:3306/didcs?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

elasticsearch:
    restClient-url: 172.17.24.99
    restClient-port: 9200

mybatis:
    configLocation: mybatis-config.xml
    basepackage: com.baiyyy.didcs.dao


eureka:
    instance:
        statusPageUrlPath: ${management.context-path}/info
        healthCheckUrlPath: ${management.context-path}/health
        preferIpAddress: true
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

#启用shutdown
#禁用密码验证
endpoints:
    shutdown:
      enabled: true
    actuator:
      sensitive: false
#禁用actuator密码验证
management:
  security:
    enabled: false

feign:
  hystrix:
      enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#zookeeper设置
zookeeper:
  baseSleepTimeMs: 1000
  maxRetries: 3
  connectString: 172.17.24.99:2181
  sessionTimeoutMs: 6000
  connectionTimeoutMs: 3000

#service通用设置
stageService:
  baseUrl: http://localhost:8762/clean-service
  serviceInvokerUrl: /serviceFlow/invoke